#!/bin/bash

# Now this script captures the exit codes so that I can run a commit hook
# That only allows commits when unifier exits 0

echo 'pytest'
pytest --cov
pt_code=$?
echo '#################################################'

# command to stop pycache from being generated by pytest.
#python -B -m pytest --cov -v

echo 'mypy'
mypy src/
mp_code=$?
echo '#################################################'


echo 'pylint'
pylint src/
pl_code=$?


# Init hook this script, and only commit if exit code is 0
codes=( $pt_code $pl_code $mp_code )
echo exit codes ${codes[@]}


# Loop through the exit codes and exit 1 if any test fails.
for x in "${codes[@]}"; do
    if [ $x != '0' ]; then
        echo fail 
        exit 1
    fi
done

echo pass
exit 0







# THIS PROJECT CURRENTLY HAS NO CUSTOM TYPES OR CLASES
# SO NO STUBS REQUIRED, IF STUBS ARE NEEDED ADD THESE LINES 
# TO THE TOP AND MAKE stubs/src & relegated/stubs/src DIRS


# stub gen doesn't check for relegated stubs
# so I back up the stubs and delete the originals
#echo 'backing up old stubs'
#cp -a stubs/src/. relegated/stubs/src
#sleep 0.4

#echo 'deleting old stubs'
#rm stubs/src/*
#sleep 0.4

#echo 'stubgen'
# This command is faster, if the stubs suck use the commented command
#stubgen --include-private --parse-only src -o stubs
#stubgen --include-private src -o stubs
#echo '#################################################'


#Copyright © 2023 Lars S.
