#!/bin/bash
# stub gen doesn't check for relegated stubs
# so I back up the stubs and delete the originals

echo 'pytest'
pytest --cov
echo '#################################################'

echo 'mypy'
mypy src/
echo '#################################################'

echo 'pylint'
pylint src/



# command to stop pycache from being generated by pytest.
#python -B -m pytest --cov -v


# THIS PROJECT CURRENTLY HAS NO CUSTOM TYPES OR CLASES
# SO NO STUBS REQUIRED, IF STUBS ARE NEEDED ADD THESE LINES 
# TO THE TOP AND MAKE stubs/src & relegated/stubs/src DIRS

#echo 'backing up old stubs'
#cp -a stubs/src/. relegated/stubs/src
#sleep 0.4

#echo 'deleting old stubs'
#rm stubs/src/*
#sleep 0.4

#echo 'stubgen'
# This command is faster, if the stubs suck use the commented command
#stubgen --include-private --parse-only src -o stubs
#stubgen --include-private src -o stubs
#echo '#################################################'


#Copyright © 2023 Lars S.
